global:
  scrape_interval: 5s # Recolhe métricas a cada 5 segundos

scrape_configs:
  - job_name: 'stockflow-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # 'host.docker.internal' permite que o container do Prometheus aceda à sua máquina local
      # onde a aplicação Spring Boot está a correr (porta 8080)
      - targets: ['host.docker.internal:8080']